[secrets]
STRIPE_KEY   = { from = "secretenv://stripe-key" }
DB_URL       = { from = "secretenv://db-url" }
REDIS_URL    = { from = "secretenv://redis-url" }
DATADOG_KEY  = { from = "secretenv://datadog-key" }

LOG_LEVEL = { default = "debug" }
