[secrets]
STRIPE_KEY      = { from = "secretenv://stripe-key" }
DATABASE_URL    = { from = "secretenv://database-url" }
DATADOG_API_KEY = { from = "secretenv://datadog-api-key" }

LOG_LEVEL = { default = "info" }
APP_ENV   = { default = "production" }
