// Copyright (C) 2026 Mandeep Patel
// SPDX-License-Identifier: AGPL-3.0-only

//! `init_project` — scaffold `secretenv.toml` from `.env` key names.
//!
//! Reads `.env` line-by-line, extracts the KEY portion of every
//! `KEY=VALUE` line (skipping blanks + comments), and proposes a
//! `secretenv.toml` mapping each key to a `secretenv://<key>` alias
//! placeholder. **VALUES ARE NEVER READ.** The `.env` parsing
//! deliberately stops at the `=` sign and discards the rest of the
//! line — even the parsing code path cannot accidentally surface a
//! secret value.
//!
//! The proposed manifest's TOML body is built deterministically:
//! keys appear in source order (matching `.env`); each key gets a
//! `[secrets.<KEY>] from = "secretenv://<key_lowercase>"` block.
//! The operator + agent decide whether to refine the alias names
//! before applying.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

/// Result of [`scaffold`]: detected key names + the proposed TOML
/// body. The caller decides whether to write `proposed_toml` to
/// `manifest_path` based on the `apply` flag + mutation policy.
pub struct Scaffold {
    /// Env-var key names detected in `.env`, in source order. Empty
    /// when no `.env` was found.
    pub detected_keys: Vec<String>,
    /// Whether a `.env` file was present in `cwd`.
    pub env_file_found: bool,
    /// Whether a `secretenv.toml` already existed at `manifest_path`
    /// before this call.
    pub manifest_already_existed: bool,
    /// Absolute path of `secretenv.toml` the proposal targets.
    pub manifest_path: PathBuf,
    /// Body the proposal would write to `manifest_path`. Always
    /// includes a top-comment block explaining the file's purpose
    /// + reminding the operator that alias names are placeholders.
    pub proposed_toml: String,
}

/// Inspect `cwd` for a `.env`, build the proposed manifest, return
/// both. NO file is written here — that's the caller's decision
/// (depending on the `apply` flag + mutation policy).
///
/// # Errors
///
/// - `cwd` does not exist or cannot be canonicalized.
/// - `.env` exists but cannot be read (e.g. permission denied).
pub fn scaffold(cwd: &Path) -> Result<Scaffold> {
    let cwd = cwd
        .canonicalize()
        .with_context(|| format!("canonicalizing working_directory `{}`", cwd.display()))?;
    let manifest_path = cwd.join("secretenv.toml");
    let manifest_already_existed = manifest_path.exists();
    let env_path = cwd.join(".env");
    let env_file_found = env_path.exists();

    let detected_keys = if env_file_found { parse_env_keys(&env_path)? } else { Vec::new() };

    let proposed_toml = render_manifest(&detected_keys, env_file_found);

    Ok(Scaffold {
        detected_keys,
        env_file_found,
        manifest_already_existed,
        manifest_path,
        proposed_toml,
    })
}

/// Read `.env` line-by-line and return KEY portions only. Stops at
/// `=` per line; never reads past the equals sign. Skips blanks and
/// `#`-prefixed comments. `export FOO=...` is supported (strips the
/// `export` prefix).
fn parse_env_keys(path: &Path) -> Result<Vec<String>> {
    let body = std::fs::read_to_string(path)
        .with_context(|| format!("reading `.env` at `{}`", path.display()))?;
    let mut keys = Vec::new();
    for line in body.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let line = trimmed.strip_prefix("export ").unwrap_or(trimmed);
        let Some(eq_idx) = line.find('=') else {
            continue;
        };
        let key = line[..eq_idx].trim();
        if !key.is_empty() && is_valid_env_var_name(key) {
            keys.push(key.to_owned());
        }
    }
    Ok(keys)
}

fn is_valid_env_var_name(s: &str) -> bool {
    s.chars().enumerate().all(|(i, c)| {
        if i == 0 {
            c.is_ascii_alphabetic() || c == '_'
        } else {
            c.is_ascii_alphanumeric() || c == '_'
        }
    })
}

/// Build the proposed manifest TOML body. Always includes a
/// top-comment block; emits a placeholder `[secrets]` section even
/// when no keys were detected so the file is immediately editable.
fn render_manifest(keys: &[String], env_file_found: bool) -> String {
    let mut out = String::with_capacity(512);
    out.push_str(
        "# Generated by `secretenv mcp init_project`.\n\
         # Each [secrets.*] entry maps an env-var name to a SecretEnv alias.\n\
         # Edit the `from = \"secretenv://...\"` URIs to point at the actual\n\
         # registry aliases you want (run `secretenv mcp list_aliases` to see\n\
         # what is already defined).\n",
    );
    if !env_file_found {
        out.push_str(
            "# No `.env` file was found in this directory; this manifest\n\
             # is empty — add `[secrets.NAME] from = \"secretenv://...\"` blocks\n\
             # by hand or re-run init_project after dropping a `.env` here.\n",
        );
    }
    out.push('\n');
    out.push_str("[secrets]\n");
    for key in keys {
        let alias = key.to_lowercase();
        let _ = writeln!(out, "{key} = {{ from = \"secretenv://{alias}\" }}");
    }
    if keys.is_empty() {
        out.push_str("# (no entries yet)\n");
    }
    out
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;
    use std::io::Write;

    fn write_env(dir: &Path, body: &str) -> PathBuf {
        let p = dir.join(".env");
        let mut f = std::fs::File::create(&p).unwrap();
        f.write_all(body.as_bytes()).unwrap();
        p
    }

    #[test]
    fn parses_typical_env_file() {
        let dir = tempfile::tempdir().unwrap();
        write_env(
            dir.path(),
            "# comment\nDATABASE_URL=postgres://foo\nexport STRIPE_KEY=sk_test_abc\n\nLOG_LEVEL=info\n",
        );
        let s = scaffold(dir.path()).unwrap();
        assert_eq!(s.detected_keys, vec!["DATABASE_URL", "STRIPE_KEY", "LOG_LEVEL"]);
        assert!(s.env_file_found);
        assert!(s
            .proposed_toml
            .contains(r#"DATABASE_URL = { from = "secretenv://database_url" }"#));
    }

    #[test]
    fn empty_cwd_no_env_produces_empty_manifest_with_comments() {
        let dir = tempfile::tempdir().unwrap();
        let s = scaffold(dir.path()).unwrap();
        assert!(s.detected_keys.is_empty());
        assert!(!s.env_file_found);
        assert!(s.proposed_toml.contains("(no entries yet)"));
    }

    #[test]
    fn rejects_invalid_env_var_names() {
        let dir = tempfile::tempdir().unwrap();
        // `1FOO` (starts with digit), `BA-D` (hyphen) — both rejected.
        write_env(dir.path(), "VALID=x\n1FOO=y\nBA-D=z\n_UNDERSCORE=w\n");
        let s = scaffold(dir.path()).unwrap();
        assert_eq!(s.detected_keys, vec!["VALID", "_UNDERSCORE"]);
    }
}
